### ISSUE TITLE
Add suppor for thin-walls mazes

### ISSUE THREAD

**Issue by Adrijaned** [Terasology/MazeAPIs#2]
Thin-walls mazes are just like thick walls, except in thick-walls mazes both walls and corridors take one tile. In thin-walls, only corridors take full tiles, while walls are to be considered infinitely thin separators between corridors.

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
